services:
  elasticsearch:
    build:
      context: .
      dockerfile: servers/elasticsearch/Dockerfile
    container_name: es01-test
    environment:
      - TZ=Asia/Tokyo
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.12
    container_name: kib01-test
    environment:
      - TZ=Asia/Tokyo
      - ELASTICSEARCH_HOSTS=http://es01-test:9200
    ports:
      - 5601:5601
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
