
# ============================== Filebeat modules ==============================
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

# ================================= Dashboards =================================
setup.dashboards.enabled: true

# ======================= Elasticsearch template setting =======================
setup.template.settings:
  index.number_of_shards: 1

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            contains:
              docker.container.image: nginx
          config:
            - module: nginx
              access:
                enabled: true
                input:
                  type: container
                  paths:
                    - /var/lib/docker/containers/${data.docker.container.id}/*.log
                  stream: stdout
              error:
                enabled: true
                input:
                  type: container
                  paths:
                    - /var/lib/docker/containers/${data.docker.container.id}/*.log
                  stream: stderr

processors:
- add_cloud_metadata: ~

# =================================== Kibana ===================================
setup.kibana:
  host: "kibana:5601"
  username: "elastic"
  password: "Admin123"

# ================================== Outputs ===================================
# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "Admin123"
  ssl:
    enabled: true
##    ssl.certificate_authorities: ["/etc/filebeat/certs/ca/ca.crt"]
    verification_mode: none
